#include <stdio.h>
#include <stdlib.h>
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

/* generated by luajit -b -t h from the corresponding src Lua files */
#include "core_bc.h"
#include "sextant_chars_bc.h"
#include "block_fonts_bc.h"
#include "big_font_bc.h"
#include "med_font_bc.h"
#include "fake_fetcher_bc.h"
#include "fetch_cpu_average_bc.h"
#include "fetch_mem_bc.h"
#include "fetch_top_bc.h"
#include "mod_cpu_bc.h"
#include "mod_mem_bc.h"
#include "mod_top_bc.h"

static void preload(lua_State *L, const char *name, const char *bc, size_t bc_len) {
	if (luaL_loadbuffer(L, bc, bc_len, name) != 0) {
		fprintf(stderr, "resmon: failed to preload module '%s': %s\n", name, lua_tostring(L, -1));
		exit(1);
	}
	lua_setfield(L, -2, name);
}

static void push_arg_table(lua_State *L, int argc, char **argv) {
	lua_newtable(L);
	for (int i = 0; i < argc; i++) {
		lua_pushstring(L, argv[i]);
		lua_rawseti(L, -2, i);
	}
	lua_setglobal(L, "arg");
}

int main(int argc, char **argv) {
	lua_State *L = luaL_newstate();
	luaL_openlibs(L);

	push_arg_table(L, argc, argv);

	lua_getglobal(L, "package");
	lua_getfield(L, -1, "preload");

	preload(L, "sextant_chars", (const char *)luaJIT_BC_sextant_chars, luaJIT_BC_sextant_chars_SIZE);
	preload(L, "block_fonts", (const char *)luaJIT_BC_block_fonts, luaJIT_BC_block_fonts_SIZE);
	preload(L, "big_font", (const char *)luaJIT_BC_big_font, luaJIT_BC_big_font_SIZE);
	preload(L, "med_font", (const char *)luaJIT_BC_med_font, luaJIT_BC_med_font_SIZE);
	preload(L, "fake_fetcher", (const char *)luaJIT_BC_fake_fetcher, luaJIT_BC_fake_fetcher_SIZE);
	preload(L, "fetch_cpu_average", (const char *)luaJIT_BC_fetch_cpu_average, luaJIT_BC_fetch_cpu_average_SIZE);
	preload(L, "fetch_mem", (const char *)luaJIT_BC_fetch_mem, luaJIT_BC_fetch_mem_SIZE);
	preload(L, "fetch_top", (const char *)luaJIT_BC_fetch_top, luaJIT_BC_fetch_top_SIZE);
	preload(L, "mod_cpu", (const char *)luaJIT_BC_mod_cpu, luaJIT_BC_mod_cpu_SIZE);
	preload(L, "mod_mem", (const char *)luaJIT_BC_mod_mem, luaJIT_BC_mod_mem_SIZE);
	preload(L, "mod_top", (const char *)luaJIT_BC_mod_top, luaJIT_BC_mod_top_SIZE);
	preload(L, "core", (const char *)luaJIT_BC_core, luaJIT_BC_core_SIZE);

	lua_pop(L, 2);

	if (luaL_dostring(L, "require('core')") != 0) {
		fprintf(stderr, "resmon: fatal error: %s\n", lua_tostring(L, -1));
		lua_close(L);
		return 1;
	}

	lua_close(L);
	return 0;
}

/* vim: filetype=c foldmethod=marker foldmarker=>{,>} */
